"""Generate the supported flat-message profile from the authoritative descriptor."""

import argparse
import json
import os
import re
from pathlib import Path
import subprocess
import tempfile
from google.protobuf import descriptor_pb2

ROOT = Path(__file__).resolve().parents[2]
PROTOCOL = ROOT / "protocol"
KIND_BODY = {
    1: "get_device_info",
    2: "get_status",
    3: "get_health",
    11: "device_info",
    12: "status",
    13: "health",
    14: "error",
    21: "status",
    22: "health",
}


def guard_protobuf_wire_types(path, messages):
    """Harden micropb 0.6 output using the same descriptor as the adapters.

    Known field numbers with another wire type are unknown fields in Protobuf.
    Guard the generated match arms so their existing fallback skips them, rather
    than interpreting their bytes as the expected type. No extra parsing pass or
    runtime schema is needed. Fail generation if the upstream output changes.
    """
    source = path.read_text()
    wire_types = {2: 5, 8: 0, 9: 2, 11: 2, 13: 0, 14: 0}
    for name, message in messages.items():
        pattern = rf"(impl ::micropb::MessageDecode for {name} \{{)(.*?)(?=\n        impl |\Z)"
        matches = list(re.finditer(pattern, source, re.S))
        assert len(matches) == 1, f"Expected one decoder for {name}"
        match = matches[0]
        body = match.group(2)
        for field in message.field:
            arm = rf"\b{field.number}u32 => \{{"
            replacement = (
                f"{field.number}u32 if tag.wire_type() == {wire_types[field.type]} => {{"
            )
            body, count = re.subn(arm, replacement, body)
            assert count == 1, f"Expected one decoder arm for {name}.{field.name}"
        source = source[:match.start(2)] + body + source[match.end(2):]
    path.write_text(source, newline="\n")


def generate(directory):
    profile = json.loads((PROTOCOL / "profile.json").read_text())
    subprocess.run(
        [
            os.sys.executable,
            "-m",
            "grpc_tools.protoc",
            f"-I{PROTOCOL}",
            f"--descriptor_set_out={directory}/schema.pb",
            f"--python_out={directory}",
            str(PROTOCOL / "messaging.proto"),
        ],
        check=True,
    )
    file = descriptor_pb2.FileDescriptorSet.FromString(
        (directory / "schema.pb").read_bytes()
    ).file[0]
    messages = {m.name: m for m in file.message_type}
    enums = {e.name: {v.name: v.number for v in e.value} for e in file.enum_type}
    shapes = {}
    code = [
        "// Generated by tools/message-demo/generate.py; do not edit.",
        f'pub const MAX_BODY: usize = {profile["max_body_bytes"]};',
        "use serde::{Deserialize, Serialize};",
        '#[cfg(feature = "csv")]',
        "use crate::{CodecError, cells::{Cells, cell, push_cell}};",
    ]

    def typ(m, f):
        if f.type == 9:
            return f'heapless::String<{profile["string_max_utf8_bytes"][m+"."+f.name]}>'
        if f.type == 11:
            return f.type_name.split(".")[-1]
        return {13: "u32", 14: "i32", 2: "f32", 8: "bool"}[f.type]

    for name, m in messages.items():
        shapes[name] = {}
        code += [
            "#[derive(Debug, Default, Clone, PartialEq, Serialize, Deserialize)]",
            "#[serde(deny_unknown_fields)]",
            f"pub struct {name} {{",
        ]
        for f in m.field:
            assert f.label != 3, "Repeated fields unsupported by prototype adapter"
            assert (
                f.type == 11 or f.proto3_optional
            ), "Scalar fields must use explicit optional presence"
            assert (
                f.type != 11 or name == "Envelope"
            ), "Only Envelope body messages are supported"
            t = typ(name, f)
            shapes[name][f.name] = {
                "type": f.type,
                "message": f.type_name.split(".")[-1] if f.type == 11 else None,
                "enum": f.type_name.split(".")[-1] if f.type == 14 else None,
                "capacity": profile["string_max_utf8_bytes"].get(name + "." + f.name),
            }
            code += [
                '    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "crate::present")]',
                f"    pub {f.name}: Option<{t}>,",
            ]
        code += ["}"]
        # Convert the flat optional model to micropb, whose oneof is an enum.
        code += [
            '#[cfg(feature = "protobuf")]',
            "#[allow(unused_mut, unused_variables)]",
            f"impl {name} {{",
            f"pub fn to_pb(&self) -> crate::pb::{name} {{",
            f"let mut output = crate::pb::{name}::default();",
        ]
        for f in m.field:
            if f.type == 11:
                variant = "".join(x.title() for x in f.name.split("_"))
                code += [
                    f"if let Some(value) = &self.{f.name} {{ output.body = Some(crate::pb::Envelope_::Body::{variant}(value.to_pb())); }}"
                ]
            else:
                expr = (
                    "(*value).into()"
                    if f.type == 14
                    else "value.clone()" if f.type == 9 else "*value"
                )
                code += [
                    f"if let Some(value) = &self.{f.name} {{ output.set_{f.name}({expr}); }}"
                ]
        code += [
            "output",
            "}",
            f"pub fn from_pb(input: crate::pb::{name}) -> Self {{",
            "let mut output = Self::default();",
        ]
        for f in m.field:
            if f.type == 11:
                continue
            expr = (
                f"input.{f.name}.map(|value| value.0)"
                if f.type == 14
                else f"input.{f.name}"
            )
            code += [f"output.{f.name} = {expr};"]
        if name == "Envelope":
            code += ["if let Some(body) = input.body { match body {"]
            for f in m.field:
                if f.type != 11:
                    continue
                variant = "".join(x.title() for x in f.name.split("_"))
                t = typ(name, f)
                code += [
                    f"crate::pb::Envelope_::Body::{variant}(v) => output.{f.name} = Some({t}::from_pb(v)),"
                ]
            code += ["}}"]
        code += ["output", "}", "}"]
    envelope = messages["Envelope"]
    body_types = {
        f.name: f.type_name.split(".")[-1] for f in envelope.field if f.type == 11
    }
    code += [
        '#[cfg(feature = "csv")]',
        "impl Envelope {",
        "pub fn to_cells(&self) -> Result<Cells, CodecError> {",
        "let mut cells = Cells::new();",
    ]
    for name in profile["common_csv_columns"]:
        code += [f"push_cell(&mut cells, self.{name}.as_ref())?;"]
    code += ["match self.kind {"]
    for kind, body in KIND_BODY.items():
        code += [
            f"Some({kind}) => {{ let body = self.{body}.as_ref().ok_or(CodecError::Validation)?;"
        ]
        for name in profile["body_csv_columns"][body]:
            code += [f"push_cell(&mut cells, body.{name}.as_ref())?;"]
        code += ["let _ = body; },"]
    code += [
        "_ => return Err(CodecError::Validation),",
        "}",
        "Ok(cells)",
        "}",
        "pub fn from_cells(cells: &Cells) -> Result<Self, CodecError> {",
        "if cells.len() < 8 { return Err(CodecError::Decode); }",
        "let mut output = Self::default();",
    ]
    for i, name in enumerate(profile["common_csv_columns"]):
        code += [f"output.{name} = cell(&cells[{i}])?;"]
    code += ["match output.kind {"]
    for kind, body in KIND_BODY.items():
        cols = profile["body_csv_columns"][body]
        t = body_types[body]
        code += [
            f"Some({kind}) => {{ if cells.len() != {8+len(cols)} {{ return Err(CodecError::Decode); }} output.{body} = Some({t} {{"
        ]
        for i, name in enumerate(cols):
            code += [f"{name}: cell(&cells[{i+8}])?,"]
        code += ["}); },"]
    code += ["_ => return Err(CodecError::Validation),", "}", "Ok(output)", "}", "}"]
    model = directory / "model.rs"
    model.write_text("\n".join(code) + "\n", newline="\n")
    subprocess.run(["rustfmt", "+1.90.0", "--edition", "2024", str(model)], check=True)
    subprocess.run(
        [
            "cargo",
            "+1.90.0",
            "run",
            "--locked",
            "--quiet",
            "--manifest-path",
            str(ROOT / "tools/message-demo/generator/Cargo.toml"),
            "--target",
            host_target(),
            "--",
            str(PROTOCOL / "profile.json"),
            str(directory / "schema.pb"),
            str(directory / "protobuf.rs"),
        ],
        check=True,
    )
    guard_protobuf_wire_types(directory / "protobuf.rs", messages)
    (directory / "schema.py").write_text(
        "# Generated; do not edit.\nSHAPES = "
        + repr(shapes)
        + "\nENUMS = "
        + repr(enums)
        + "\nKIND_BODY = "
        + repr(KIND_BODY)
        + "\nPROFILE = "
        + repr(profile)
        + "\n",
        newline="\n",
    )
    lines = [
        "# Generated message reference",
        "",
        "Source: `Rust/protocol/messaging.proto`. Application semantics remain in CONTRACT.md.",
        "",
    ]
    for name, m in messages.items():
        lines += ["## " + name, "", "| Field | Tag | Type |", "|---|---:|---|"]
        for f in m.field:
            lines += [f"| {f.name} | {f.number} | {typ(name,f)} |"]
        lines += [""]
    for name, values in enums.items():
        lines += ["## " + name, "", "| Value | Number |", "|---|---:|"]
        lines += [f"| {key} | {value} |" for key, value in values.items()]
        lines += [""]
    (directory / "REFERENCE.md").write_text("\n".join(lines), newline="\n")
    return {
        "model.rs": ROOT / "messaging/src/generated/model.rs",
        "protobuf.rs": ROOT / "messaging/src/generated/protobuf.rs",
        "schema.py": ROOT / "tools/message-demo/python/generated/schema.py",
        "messaging_pb2.py": ROOT
        / "tools/message-demo/python/generated/messaging_pb2.py",
        "REFERENCE.md": ROOT / "docs/messaging/REFERENCE.md",
    }


def host_target():
    return next(
        line.split(": ", 1)[1]
        for line in subprocess.check_output(
            ["rustc", "+1.90.0", "-vV"], text=True
        ).splitlines()
        if line.startswith("host: ")
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    with tempfile.TemporaryDirectory() as temp:
        directory = Path(temp)
        for filename, destination in generate(directory).items():
            content = (directory / filename).read_bytes()
            if args.check:
                if not destination.exists() or destination.read_bytes() != content:
                    raise SystemExit(f"Generated file differs: {destination}")
            else:
                destination.parent.mkdir(parents=True, exist_ok=True)
                destination.write_bytes(content)
    print("Generated outputs verified." if args.check else "Generated outputs written.")
