[package]
name = "messaging-codec"
version = "0.1.0"
edition = "2024"
publish = false

[features]
default = ["csv", "json", "protobuf"]
csv = ["dep:csv-core", "dep:ryu"]
json = ["dep:serde-json-core"]
protobuf = ["dep:micropb"]

[dependencies]
micropb = { optional = true, version = "=0.6.0", default-features = false, features = ["container-heapless-0-9", "encode", "decode"] }
heapless = { version = "=0.9.3", features = ["serde"] }
serde = { version = "=1.0.228", default-features = false, features = ["derive"] }
serde-json-core = { version = "=0.6.0", optional = true }
csv-core = { version = "=0.1.13", optional = true }
ryu = { version = "=1.0.23", optional = true }


[[example]]
name = "no_alloc"
path = "examples/no_alloc.rs"
